name: Deploy Svelte to Google Cloud VM

on:
  push:
    branches:
      - main # Change this to match your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: prisma://${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build application
        run: npm run build

      - name: Create deployment package
        run: |
          tar czf deploy.tar.gz \
            build \
            package*.json \
            prisma \
            node_modules/@prisma \
            node_modules/.prisma

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: deploy.tar.gz

  transfer:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Transfer to VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_IP: ${{ secrets.VM_IP }}
          VM_PATH: '/home/${{ secrets.VM_USER }}/app'
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          scp -i private_key -o StrictHostKeyChecking=no deploy.tar.gz $VM_USER@$VM_IP:$VM_PATH/
          rm -f private_key

  deploy:
    needs: transfer
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
          DATABASE_URL: prisma://${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_IP: ${{ secrets.VM_IP }}
          VM_PATH: '/home/${{ secrets.VM_USER }}/app'
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          ssh -i private_key -o StrictHostKeyChecking=no $VM_USER@$VM_IP << EOF
            # Load environment
            source ~/.bashrc
            source ~/.profile
            export NVM_DIR="\$HOME/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
            
            cd $VM_PATH
            tar xzf deploy.tar.gz
            rm deploy.tar.gz
            echo "DATABASE_URL=prisma://$DATABASE_URL" > .env
            echo "DIRECT_URL=$DIRECT_URL" >> .env
            echo "PORT=3000" >> .env
            echo "ORIGIN=$PUBLIC_URL" >> .env
            
            # Use full paths if needed
            if command -v npm &> /dev/null; then
              npm ci --production --ignore-scripts
            else
              echo "Using NVM npm"
              \$NVM_DIR/versions/node/*/bin/npm ci --production --ignore-scripts
            fi
            
            if command -v pm2 &> /dev/null; then
              pm2 restart app || pm2 start "node build" --name "app"
            else
              echo "Using global pm2"
              \$NVM_DIR/versions/node/*/bin/pm2 restart app || \$NVM_DIR/versions/node/*/bin/pm2 start "node build" --name "app"
            fi
          EOF
          rm -f private_key
