name: Deploy Svelte to Google Cloud VM

on:
  push:
    branches:
      - main # Change this to match your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: prisma://${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build application
        run: npm run build

      - name: Deploy to Google Cloud VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_IP: ${{ secrets.VM_IP }}
          VM_PATH: '/home/${{ secrets.VM_USER }}/app' # Update this with the correct path

        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          # Create SSH config to disable host key checking
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          # Deploy files
          scp -i private_key -o StrictHostKeyChecking=no -r ./* $VM_USER@$VM_IP:$VM_PATH
          ssh -i private_key -o StrictHostKeyChecking=no $VM_USER@$VM_IP << EOF
            cd $VM_PATH
            echo "DATABASE_URL=prisma://$DATABASE_URL" > .env
            echo "DIRECT_URL=$DIRECT_URL" >> .env
            echo "PORT=3000" >> .env
            echo "ORIGIN=$PUBLIC_URL" >> .env
            npm ci
            npm run build
            pm2 restart app || pm2 start "node build" --name "app"
          EOF
          rm -f private_key
